import HeroSection from '../components/HeroSection/heroSection';
import Skills from '../components/Skills/Skills'
import Experience from '../components/Experience/Experience';
import Project from '../components/Project/Project';
import { useState } from 'react';

function MidSection() {

  let [project,setProject] = useState("Frontend_Developer")

    let projects = {
        'Frontend_Developer':[
        {
        "link":"https://github.com/YASHSAXEN/Notemaker_using_javascript",
        "skills":["HTML","CSS","Javascript"],
        "title":"Notemaker",
        "desc":"The NoteMaker App is a simple and efficient web application designed for users  to create, edit, and store notes seamlessly. Developed using HTML, CSS, and JavaScript, this lightweight application leverages the browser`s local storage to ensure a hassle-free note-taking experience without the need for an external database",
        "links":"https://notemaker-1.netlify.app"
        },
        {
        "link":"https://github.com/YASHSAXEN/Socialmedia_clone",
        "skills":["HTML","CSS","ReactJS","Javascript"],
        "title":"Social Media UI Clone",
        "desc":"The Facebook Frontend Clone project is a meticulous recreation of the Facebook user interface using React.js, HTML, and CSS. This endeavor aims to provide a hands-on learning experience for developers interested in mastering React.js while replicating the familiar and intuitive design of the world`s leading social media platform.",
        "links":""
        },
        {
        "link":"https://github.com/YASHSAXEN/Car_Price_Prediction_System",
        "skills":["HTML","CSS","Python","Flask","Machine Learning"],
        "title":"Car Price Prediction System",
        "desc":"The Car Price prediction system using machine learning, Python, and Flask is a web-based application that predicts the selling price of a used car based on several input factors such as the car`s model, year,mileage, fuel type, and transmission type",
        "links":""
        }],
        'FullStack_Developer':[
            {
            "link":"https://github.com/YASHSAXEN/Ai-image-detector.git",
            "skills":["HTML","CSS","Javascript","Django","SQL","Deep Learning"],
            "title":"AI Generated Image Detector",
            "desc":"AI Image Detector is a web application which helps the people to differentiate between the real image s and the images generated by AI. For differentiation between real and AI generated this app use pretrained model of CNN. This app give the output in percentage form which tells how much percentage the chance of the image is to be real or AI.",
            "links":""
            },
            {
            "link":"https://github.com/YASHSAXEN/blogapp.git",
            "skills":["HTML","CSS","Javascript","Django",'SQL'],
            "title":"PokiBlog Start writting the blogs",
            "desc":"Created a blog website that allows users to write their own blogs, read blogs posted by others, and comment on others' blogs. The frontend was developed using HTML, CSS, and JavaScript to ensure a responsive and user-friendly interface. The backend was built with Django, providing a robust and scalable framework for handling user authentication, blog creation, and comments.",
            "links":'https://pokiblog.onrender.com'
            },
            {
            "link":"https://github.com/YASHSAXEN/ChatApp",
            "skills":["HTML","CSS","Javascript","Django",'SQL','Websocket','Cloudinary'],
            "title":"PokiChat Chat with your friends",
            "desc":"Developed a real-time group chat web application using HTML, CSS, and JavaScript for the frontend, and Django for the backend. Integrated WebSockets for instant messaging, SQLite3 for text data storage, and Cloudinary for managing images. Implemented features for private group creation, ensuring data is deleted once all members leave to maintain privacy.",
            "links":"https://pokichat.onrender.com"
        }],
        'Data_Analyst':[
                {
                "link":"https://github.com/YASHSAXEN/Sales_Data_Analysis",
                "skills":["Python","Pandas","Seaborn", "Matplotlib","Tableau"],
                "title":"Sales Data Analysis",
                "desc":"The Sales Data Analysis and Dashboard project present a comprehensive exploration and visualization of the sales data from a superstore. This project employs Python for data analysis and Tableau for creating an interactive and insightful dashboard. The aim is to extract meaningful patterns, trends, and insights from the sales data.",
                "links":"https://public.tableau.com/views/SalesDataAnalysis_17042739086040/Dashboard1?:language=en-US&publish=yes&:display_count=n&:origin=viz_share_link"
                },
                {
                "link":"https://github.com/YASHSAXEN/Diabetes_Prediction_System",
                "skills":["HTML","CSS","Python","Flask","Machine Learning"],
                "title":"Diabetes Prediction System",
                "desc":"The Facebook Frontend Clone project is a meticulous recreation of the Facebook user interface using React.js, HTML, and CSS. This endeavor aims to provide a hands-on learning experience for developers interested in mastering React.js while replicating the familiar and intuitive design of the world`s leading social media platform.",
                "links":""
                },
                {
                "link":"https://github.com/YASHSAXEN/Car_Price_Prediction_System",
                "skills":["HTML","CSS","Python","Flask","Machine Learning"],
                "title":"Car Price Prediction System",
                "desc":"The Diabetes prediction system using machine learning, Python, and Flask is a sophisticated web-based application that uses machine learning algorithms to predict the likelihood of a person developing diabetes.",
                "links":""
        }]
}
  return (
    <>
        <HeroSection></HeroSection>
        <Skills></Skills>
        <Experience></Experience>
        <Project projects={projects} setProject={setProject} project={project}></Project>
    </>
  )
}

export default MidSection